# Generated by Django 5.2 on 2025-05-07 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_news_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='content',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='title',
            new_name='name',
        ),
    ]
